// <auto-generated />
using System;
using Estoque.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Estoque.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913224842_AdicionaOutboxDeConfirmacoes")]
    partial class AdicionaOutboxDeConfirmacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Estoque.Api.Domain.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_itens_pedido");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_itens_pedido_pedido_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_pedido_produto_id");

                    b.ToTable("itens_pedido", null, t =>
                        {
                            t.HasCheckConstraint("ck_itens_pedido_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("Estoque.Api.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("ClienteCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cliente_cpf");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("cliente_email");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto");

                    b.Property<DateTimeOffset?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<decimal>("Frete")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("frete");

                    b.Property<DateTimeOffset?>("PagoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pedidos_status");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Estoque.Api.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo_unitario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sku");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_sku");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_custo_nao_negativo", "custo_unitario >= 0");

                            t.HasCheckConstraint("ck_produtos_preco_positivo", "preco > 0");

                            t.HasCheckConstraint("ck_produtos_quantidade_nao_negativa", "quantidade >= 0");
                        });
                });

            modelBuilder.Entity("Estoque.Api.Features.Pedidos.ConfirmacaoPendente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset?>("EnviadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_em");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<DateTimeOffset>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("pk_confirmacoes_pendentes");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_confirmacoes_pendentes_pedido_id");

                    b.HasIndex("ProximaTentativaEm")
                        .HasDatabaseName("ix_confirmacoes_pendentes_proxima_tentativa_em")
                        .HasFilter("enviada_em IS NULL");

                    b.ToTable("confirmacoes_pendentes", (string)null);
                });

            modelBuilder.Entity("Estoque.Api.Domain.ItemPedido", b =>
                {
                    b.HasOne("Estoque.Api.Domain.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_pedidos_pedido_id");

                    b.HasOne("Estoque.Api.Domain.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_produtos_produto_id");
                });

            modelBuilder.Entity("Estoque.Api.Features.Pedidos.ConfirmacaoPendente", b =>
                {
                    b.HasOne("Estoque.Api.Domain.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_confirmacoes_pendentes_pedidos_pedido_id");
                });

            modelBuilder.Entity("Estoque.Api.Domain.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
